## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])

# Display the first few rows of the updated DataFrame
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column
unique_values = application_df.nunique()

# Display the result
print(unique_values)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# View the value counts for APPLICATION_TYPE
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

# Display the result
print(application_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500

# Create a list of application types to be replaced
application_types_to_replace = list(application_type_counts[application_type_counts < cutoff_value].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [8]:
# View the value counts for CLASSIFICATION
classification_counts = application_df['CLASSIFICATION'].value_counts()

# Display the result
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [9]:
# Filter and display classifications with counts greater than 1
classification_counts_gt_1 = classification_counts[classification_counts > 1]

# Display the result
print(classification_counts_gt_1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# Choose a cutoff value (e.g., 1000)
cutoff_value = 1000

# Create a list of classifications to be replaced with "Other"
classifications_to_replace = list(classification_counts[classification_counts < cutoff_value].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [13]:
# Convert categorical data to numeric using pd.get_dummies
application_df_encoded = pd.get_dummies(application_df, columns=['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'])

# Display the first few rows of the encoded DataFrame
application_df_encoded.head()

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,5000,1,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,108590,1,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,5000,0,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
3,6692,1,False,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,142590,1,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [14]:
# Define the target variable
target_column = 'IS_SUCCESSFUL'

# Split the DataFrame into features (X) and target (y)
X = application_df_encoded.drop(columns=[target_column])  # Features
y = application_df_encoded[target_column]                 # Target

# Display the shapes of the resulting arrays
print(f"Features shape: {X.shape}")
print(f"Target shape: {y.shape}")

Features shape: (34299, 44)
Target shape: (34299,)

In [15]:
# Import the train_test_split function
from sklearn.model_selection import train_test_split

# Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2,    # 20% of the data for testing
                                                    random_state=42)  # Ensures reproducibility

# Display the shapes of the resulting datasets
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")
print(f"Training target shape: {y_train.shape}")
print(f"Testing target shape: {y_test.shape}")

Training features shape: (27439, 44)
Testing features shape: (6860, 44)
Training target shape: (27439,)
Testing target shape: (6860,)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [18]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
# Define the number of input features
input_features = X_train.shape[1] 

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=64, activation='relu', input_shape=(input_features,)))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))  # For binary classification


# Check the structure of the model
nn.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 64)                  │           2,880 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,993 (19.50 KB)

 Trainable params: 4,993 (19.50 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
# Compile the model
nn.compile(optimizer='adam',                   # Optimizer
            loss='binary_crossentropy',         # Loss function for binary classification
            metrics=['accuracy'])               # Metric to evaluate during training

In [22]:
import numpy as np
# Ensure X_train and y_train are NumPy arrays
X_train = X_train.to_numpy()  # or use X_train.values
y_train = y_train.to_numpy()  # if y_train is still a DataFrame

# Check data types and shapes
print(f"X_train type: {type(X_train)}, shape: {X_train.shape}")
print(f"y_train type: {type(y_train)}, shape: {y_train.shape}")

# Check data types
print("Data types in X_train:", X_train.dtype)  # Now this will work
print("Data types in y_train:", y_train.dtype)  # This will also work if y_train is an array

# Convert to appropriate types if necessary
X_train = X_train.astype(float)
y_train = y_train.astype(int)

# Check for missing values
print("Missing values in X_train:", np.isnan(X_train).sum())
print("Missing values in y_train:", np.isnan(y_train).sum())

# Train the model
history = nn.fit(X_train, y_train, 
                 epochs=100, 
                 batch_size=32, 
                 validation_split=0.2, 
                 verbose=1)

X_train type: <class 'numpy.ndarray'>, shape: (27439, 44)
y_train type: <class 'numpy.ndarray'>, shape: (27439,)
Data types in X_train: object
Data types in y_train: int64
Missing values in X_train: 0
Missing values in y_train: 0
Epoch 1/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 17s 13ms/step - accuracy: 0.4924 - loss: 20990.5254 - val_accuracy: 0.4829 - val_loss: 2409.5225
Epoch 2/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.4911 - loss: 24238.5293 - val_accuracy: 0.5171 - val_loss: 23410.4844
Epoch 3/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.4905 - loss: 20764.0566 - val_accuracy: 0.6266 - val_loss: 155.2336
Epoch 4/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 9s 12ms/step - accuracy: 0.5230 - loss: 6002.2310 - val_accuracy: 0.4829 - val_loss: 1635.9995
Epoch 5/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 8s 12ms/step - accuracy: 0.5411 - loss: 38437.5781 - val_accuracy: 0.5171 - val_loss: 24243.8262
Epoch 6/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.5090 - loss: 27013.3379 - val_accuracy: 0.5171 - val_loss: 51934.6133
Epoch 7/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.5170 - loss: 15755.9053 - val_accuracy: 0.5171 - val_loss: 13679.9639
Epoch 8/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.5032 - loss: 4580.6812 - val_accuracy: 0.4829 - val_loss: 2081.6951
Epoch 9/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 8s 12ms/step - accuracy: 0.4990 - loss: 4520.5176 - val_accuracy: 0.5727 - val_loss: 137.3947
Epoch 10/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.5225 - loss: 25158.3535 - val_accuracy: 0.5171 - val_loss: 679.0030
Epoch 11/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.5303 - loss: 267.2203 - val_accuracy: 0.4829 - val_loss: 411.9673
Epoch 12/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 12s 12ms/step - accuracy: 0.5126 - loss: 3977.8037 - val_accuracy: 0.5184 - val_loss: 8.9238
Epoch 13/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.5302 - loss: 505.9604 - val_accuracy: 0.5171 - val_loss: 161.0088
Epoch 14/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.5241 - loss: 2637.0398 - val_accuracy: 0.6186 - val_loss: 24.8630
Epoch 15/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.5427 - loss: 937.6085 - val_accuracy: 0.5968 - val_loss: 34.1098
Epoch 16/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.5100 - loss: 523.4833 - val_accuracy: 0.5171 - val_loss: 3426.3062
Epoch 17/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5103 - loss: 674.5394 - val_accuracy: 0.5133 - val_loss: 4.3931
Epoch 18/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5230 - loss: 699.7941 - val_accuracy: 0.4978 - val_loss: 17.7724
Epoch 19/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.5225 - loss: 91.6016 - val_accuracy: 0.5171 - val_loss: 0.7002
Epoch 20/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.5361 - loss: 0.6918 - val_accuracy: 0.5171 - val_loss: 0.6934
Epoch 21/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5391 - loss: 0.6901 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 22/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5349 - loss: 0.6908 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 23/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5353 - loss: 0.6907 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 24/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5385 - loss: 0.6903 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 25/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5366 - loss: 0.6906 - val_accuracy: 0.5171 - val_loss: 0.6929
Epoch 26/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5334 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6935
Epoch 27/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5400 - loss: 0.6900 - val_accuracy: 0.5171 - val_loss: 0.6927
Epoch 28/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5342 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6937
Epoch 29/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5349 - loss: 0.6909 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 30/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5337 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6934
Epoch 31/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5297 - loss: 0.6915 - val_accuracy: 0.5171 - val_loss: 0.6937
Epoch 32/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5432 - loss: 0.6895 - val_accuracy: 0.5171 - val_loss: 0.6928
Epoch 33/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5321 - loss: 0.6912 - val_accuracy: 0.5171 - val_loss: 0.6936
Epoch 34/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5401 - loss: 0.6900 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 35/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5299 - loss: 0.6914 - val_accuracy: 0.5171 - val_loss: 0.6933
Epoch 36/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5370 - loss: 0.6905 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 37/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5411 - loss: 0.6899 - val_accuracy: 0.5171 - val_loss: 0.6933
Epoch 38/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.5332 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6934
Epoch 39/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5390 - loss: 0.6902 - val_accuracy: 0.5171 - val_loss: 0.6930
Epoch 40/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5362 - loss: 0.6906 - val_accuracy: 0.5171 - val_loss: 0.6935
Epoch 41/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5390 - loss: 0.6902 - val_accuracy: 0.5171 - val_loss: 0.6928
Epoch 42/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5418 - loss: 0.6899 - val_accuracy: 0.5171 - val_loss: 0.6929
Epoch 43/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5311 - loss: 0.6913 - val_accuracy: 0.5171 - val_loss: 0.6942
Epoch 44/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.5358 - loss: 0.6907 - val_accuracy: 0.5171 - val_loss: 0.6928
Epoch 45/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5386 - loss: 0.6903 - val_accuracy: 0.5171 - val_loss: 0.6926
Epoch 46/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.5354 - loss: 0.6908 - val_accuracy: 0.5171 - val_loss: 0.6936
Epoch 47/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5390 - loss: 0.6902 - val_accuracy: 0.5171 - val_loss: 0.6934
Epoch 48/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5374 - loss: 0.6904 - val_accuracy: 0.5171 - val_loss: 0.6929
Epoch 49/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5364 - loss: 0.6906 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 50/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.5340 - loss: 0.6909 - val_accuracy: 0.5171 - val_loss: 0.6941
Epoch 51/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.5380 - loss: 0.6903 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 52/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.5375 - loss: 0.6904 - val_accuracy: 0.5171 - val_loss: 0.6933
Epoch 53/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.5373 - loss: 0.6904 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 54/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5390 - loss: 0.6902 - val_accuracy: 0.5171 - val_loss: 0.6930
Epoch 55/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.5363 - loss: 0.6906 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 56/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5336 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6933
Epoch 57/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.5368 - loss: 0.6905 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 58/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5334 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 59/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5335 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6934
Epoch 60/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5335 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6934
Epoch 61/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5398 - loss: 0.6900 - val_accuracy: 0.5171 - val_loss: 0.6929
Epoch 62/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5361 - loss: 0.6906 - val_accuracy: 0.5171 - val_loss: 0.6930
Epoch 63/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5377 - loss: 0.6904 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 64/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5370 - loss: 0.6905 - val_accuracy: 0.5171 - val_loss: 0.6937
Epoch 65/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5355 - loss: 0.6907 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 66/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5357 - loss: 0.6907 - val_accuracy: 0.5171 - val_loss: 0.6933
Epoch 67/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5362 - loss: 0.6906 - val_accuracy: 0.5171 - val_loss: 0.6927
Epoch 68/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5375 - loss: 0.6906 - val_accuracy: 0.5171 - val_loss: 0.6938
Epoch 69/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5427 - loss: 0.6895 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 70/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5342 - loss: 0.6909 - val_accuracy: 0.5171 - val_loss: 0.6939
Epoch 71/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5341 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 72/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5392 - loss: 0.6902 - val_accuracy: 0.5171 - val_loss: 0.6934
Epoch 73/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5340 - loss: 0.6909 - val_accuracy: 0.5171 - val_loss: 0.6936
Epoch 74/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.5362 - loss: 0.6907 - val_accuracy: 0.5171 - val_loss: 0.6934
Epoch 75/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5351 - loss: 0.6908 - val_accuracy: 0.5171 - val_loss: 0.6935
Epoch 76/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.5380 - loss: 0.6904 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 77/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5366 - loss: 0.6906 - val_accuracy: 0.5171 - val_loss: 0.6936
Epoch 78/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5356 - loss: 0.6907 - val_accuracy: 0.5171 - val_loss: 0.6935
Epoch 79/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5333 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6934
Epoch 80/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5419 - loss: 0.6898 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 81/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.5379 - loss: 0.6904 - val_accuracy: 0.5171 - val_loss: 0.6929
Epoch 82/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5433 - loss: 0.6897 - val_accuracy: 0.5171 - val_loss: 0.6929
Epoch 83/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.5364 - loss: 0.6906 - val_accuracy: 0.5171 - val_loss: 0.6933
Epoch 84/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.5321 - loss: 0.6912 - val_accuracy: 0.5171 - val_loss: 0.6936
Epoch 85/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5381 - loss: 0.6903 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 86/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5334 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 87/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5355 - loss: 0.6908 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 88/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5352 - loss: 0.6908 - val_accuracy: 0.5171 - val_loss: 0.6930
Epoch 89/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5372 - loss: 0.6905 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 90/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5401 - loss: 0.6900 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 91/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5306 - loss: 0.6914 - val_accuracy: 0.5171 - val_loss: 0.6936
Epoch 92/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5338 - loss: 0.6910 - val_accuracy: 0.5171 - val_loss: 0.6934
Epoch 93/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5306 - loss: 0.6915 - val_accuracy: 0.5171 - val_loss: 0.6936
Epoch 94/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5331 - loss: 0.6911 - val_accuracy: 0.5171 - val_loss: 0.6936
Epoch 95/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5379 - loss: 0.6903 - val_accuracy: 0.5171 - val_loss: 0.6932
Epoch 96/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5394 - loss: 0.6901 - val_accuracy: 0.5171 - val_loss: 0.6930
Epoch 97/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5335 - loss: 0.6909 - val_accuracy: 0.5171 - val_loss: 0.6931
Epoch 98/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5372 - loss: 0.6905 - val_accuracy: 0.5171 - val_loss: 0.6933
Epoch 99/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.5378 - loss: 0.6903 - val_accuracy: 0.5171 - val_loss: 0.6929
Epoch 100/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5363 - loss: 0.6906 - val_accuracy: 0.5171 - val_loss: 0.6928

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 2s - 8ms/step - accuracy: 0.6892 - loss: 0.6707
Loss: 0.6707060933113098, Accuracy: 0.6892127990722656

In [24]:
# Export our model to HDF5 file
nn.save('charity_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.